[package]
name = "rust-binary-template"
version = "0.0.0"
edition = "2021"

[commands]
lint = "cargo fmt -- --check && cargo clippy --all-targets --all-features -- -D warnings"

[dependencies]
clap = { version = "4.4.18" }
