[tasks.build]
description = "Builds the development version of the project."
run = "cargo build"

[tasks.ci]
description = "Runs the CI jobs."
run = [{ task = "build" }, { tasks = ["lint", "test"] }]

[tasks.lint]
description = "Lints the project."
run = "cargo fmt -- --check && cargo clippy --all-targets --all-features -- -D warnings"

[tasks.test]
description = "Runs the project's tests."
run = "cargo test"

[tasks."test:coverage:lcov"]
description = "Runs the project's tests and aggregates code coverage in lcov format."
run = "cargo tarpaulin --out lcov --output-dir coverage"

[tasks."test:doc"]
description = "Runs the project's doc tests."
run = "cargo test --doc"

[tasks."test:unit"]
description = "Runs the project's unit tests."
run = "cargo test --bins --lib"

[tools]
"cargo:cargo-tarpaulin" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["rust"]
