[tasks.build]
description = "Builds the development version of the project."
run = "cargo build"

[tasks.ci]
description = "Runs the CI jobs."
run = [{ task = "build" }, { tasks = ["lint", "test:coverage:lcov"] }]

[tasks.fix]
description = "Formats and fixes the code."
run = "cargo fmt && cargo clippy --all-targets --all-features --fix --allow-dirty -- -D warnings"

[tasks.lint]
description = "Lints the project."
run = "cargo fmt -- --check && cargo clippy --all-targets --all-features -- -D warnings"

[tasks.test]
description = "Runs the project's tests."
run = "cargo test"

[tasks."test:coverage"]
description = "Runs the project's tests and displays code coverage."
run = "cargo llvm-cov"

[tasks."test:coverage:lcov"]
description = "Runs the project's tests and aggregates code coverage in lcov format."
run = "mkdir -p coverage && cargo llvm-cov --lcov --output-path coverage/lcov.info"

[tasks."test:doc"]
description = "Runs the project's doc tests."
run = "cargo test --doc"

[tasks."test:unit"]
description = "Runs the project's unit tests."
run = "cargo test --bins --lib"

[tools]
"cargo:cargo-llvm-cov" = "latest"
"rust" = { version = "1.94.1", components = "clippy,llvm-tools,llvm-tools-preview,rustfmt,rust-analyzer" }
