name: Build

on:
  push:
    # This turns off running for tags
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install cargo-commander
        # cargo-tarpaulin@0.30.0 breaks the build last time around.
      - run: cargo install cargo-tarpaulin@0.29.2
      - run: cargo cmd lint
      - run: cargo cmd test:coverage:lcov
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.codecov-token }}
